services:
  postgres-db:
    image: postgres:latest
    container_name: container_troca_upe
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_troca_upe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      # Aqui estamos fazendo o mapeamento dos arquivos SQL para serem executados na inicialização do container,
      # assim, quando o container for iniciado, ele irá executar os scripts SQL presentes nas pastas mapeadas (menos os dados fictícios).
      - ./src:/docker-entrypoint-initdb.d/

volumes:
  postgres_data: